# -*- coding: utf-8 -*-
"""Session1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZchQi1QEfxAjNXiZaGhNdvj0vR7o0kEr
"""

import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

string_eins = "Hallo vom Oskar-Morgen-Stern Platz!"
string_zwei = "Hallo ihr Marsbewohner! Habt ihr Python im Einsatz?"

"""string_eins[3]

string_eins.capitalize()

string_eins.lower()

string_eins.count("e")

string_eins.find("e")

string_eins + string_zwei

string_zwei[4:12]

string_zwei.lower()

string_zwei.replace("H","J")

"""

print(string_eins[3])

print(string_eins.capitalize())

print(string_eins.lower())

print(string_eins.count("e"))

print(string_eins.find("e"))

print(string_eins + string_zwei)

print(string_zwei[4:12])

print(string_zwei.lower())

print(string_zwei.replace("H","J"))

liste = ['Storch', 'Orange', 33, 'Python', 2.18 ]

print("Initial list:", liste)
liste[2] = 666
print("List after setting element at index 2 to 666:", liste)
print("Length of list:", len(liste))
liste.append('Ni')
print("List after appending 'Ni':", liste)
liste.extend([4, 5, 3.14])
print("List after extending with [4, 5, 3.14]:", liste)
liste.insert(2, 'Taube')
print("List after inserting 'Taube' at index 2:", liste)
print("Number of occurrences of 3.14 in list:", liste.count(3.14))
print("Index of first occurrence of 3.14 in list:", liste.index(3.14))
liste.remove(3.14)
print("List after removing first occurrence of 3.14:", liste)
popped_element = liste.pop()
print("Popped element:", popped_element)
liste.reverse()
print("List after reversing:", liste)

x = 15
y = 4
print('x + y =',x+y) # sum of x and y
print('x - y =',x-y) # diff of x and y
print('x * y =',x*y)# product of x and y
print('x / y =',x/y)# x divided by y
print('x // y =',x//y)# x divided by 3, give out int instead of float
print('x ** y =',x**y)# x superscript y
x = 10
y = 12
print('x > y  is',x>y) # x bigger y?
print('x < y  is',x<y) # x smaller y?
print('x == y is',x==y) # x gleich y?
print('x != y is',x!=y) # x. ungleich y?
print('x >= y is',x>=y) # x bigger oder gleich y?
print('x <= y is',x<=y)

"""Eingabe zur Frage: „Findest du Python toll?“
Wenn Eingabe gleich "ja" oder "jep"
	Ausgabe: „Sehr gut! Ich auch!“
Sonst
	Ausgabe: „Das glaube ich dir nicht!“

"""

i = print(input("Magst du Python?"))
if i == "ja" or "jep":
  print("Very good. Me too")
# elif i == "jep":
#   print("Very good. Me too")
else:
  print("Das glaube ich dir nicht!")

"""Aufgabe 5
Gegeben ist folgende Tabelle bezüglich Luftdruck, Lufttemperatur und Jahreszeit. Aufgrund dieser Parameter wird eine Empfehlung in Textform ausgegeben. Schreiben Sie den Code in Python, der diese Tabelle nach der Eingabe der 3 Parameter abfragt und die Empfehlung ausgibt. Wenn die Eingabe nicht übereinstimmt soll ein Standardtext erscheinen.


Luftdruck	steigt	steigt	fällt	fällt
Lufttemperatur	steigt	fällt	steigt	fällt
Jahreszeit	Sommer	Winter	Sommer	Winter
Empfehlung	Text 1	Text 2	Text 3	Text 4
•	Text 1: "Pack die Badehose ein, nimm dein kleines Schwesterlein ..."
•	Text 2: "I wü, Schifoarn, foarn, foarn ..."
•	Text 3: "I'm singing in the rain ..."
•	Text 4: "Leise rieselt der Schnee ..."
•	Sonst: "Nichts Genaues weiß man nicht!"

"""

# Eingabe der Parameter
luftdruck = input("Luftdruck (steigt/fällt): ")
lufttemperatur = input("Lufttemperatur (steigt/fällt): ")
jahreszeit = input("Jahreszeit (Sommer/Winter): ")

# Ausgabe der Empfehlung basierend auf den Eingaben
if luftdruck == "steigt" and lufttemperatur == "steigt" and jahreszeit == "Sommer":
    print("Pack die Badehose ein, nimm dein kleines Schwesterlein ...")
elif luftdruck == "fällt" and lufttemperatur == "fällt" and jahreszeit == "Winter":
    print("Leise rieselt der Schnee ...")
elif luftdruck == "steigt" and lufttemperatur == "fällt" and jahreszeit == "Sommer":
    print("Nichts Genaues weiß man nicht!")
elif luftdruck == "fällt" and lufttemperatur == "steigt" and jahreszeit == "Winter":
    print("I wü, Schifoarn, foarn, foarn ...")
elif luftdruck == "fällt" and lufttemperatur == "steigt" and jahreszeit == "Sommer":
    print("Nichts Genaues weiß man nicht!")
elif luftdruck == "steigt" and lufttemperatur == "fällt" and jahreszeit == "Winter":
    print("Nichts Genaues weiß man nicht!")
elif luftdruck == "fällt" and lufttemperatur == "fällt" and jahreszeit == "Sommer":
    print("I'm singing in the rain ...")
else:
    print("Nichts Genaues weiß man nicht!")

password = "geheim"

for i in range(3):
    guess = input("Bitte geben Sie das Passwort ein: ")
    if guess == password:
        print("Willkommen auf dem Server BigMac")
        break
    else:
        print("Falsches Passwort")
else:
    print("Sooooo wird das nichts!")

# Eingabe des Bruttoeinkommens
einkommen = float(input("Geben Sie Ihr Bruttoeinkommen in Euro ein: ")


# Berechnung des Steuersatzes
if einkommen <= 11000:
    steuersatz = 0
elif einkommen <= 18000:
    steuersatz = 0.25
elif einkommen <= 31000:
    steuersatz = 0.35
elif einkommen <= 60000:
    steuersatz = 0.42
elif einkommen <= 90000:
    steuersatz = 0.48
elif einkommen <= 1000000:
    steuersatz = 0.5
else:
    steuersatz = 0.55

# Berechnung des Steuerbetrags
steuerbetrag = einkommen * steuersatz

# Ausgabe des Ergebnisses
print("Das Bruttoeinkommen beträgt:", einkommen, "Euro")
print("Der Steuersatz beträgt:", steuersatz*100, "%")
print("Der zu zahlende Steuerbetrag beträgt:", steuerbetrag, "Euro")

"""Luftdruck: steigt, steigt, fällt, fällt
Lufttemperatur: steigt, fällt, steigt, fällt
Jahreszeit: Sommer, Winter, Sommer, Winter
Empfehlung: Text 1, Text 2, Text3, Text 4
"""

for zahl in [4,5,7,11,21]:
    summe = zahl + 2
    print("Wenn ich zu", zahl, "zwei addiere, erhalte ich", summe)
print("Ich bin fertig!")

# Leere Liste erstellen
zahlen = []

# Endlosschleife
while True:
    # Eingabeaufforderung
    eingabe = input("Geben Sie eine Zahl ein (q zum Beenden): ")
    
    # Prüfen, ob der Benutzer das Programm beenden möchte
    if eingabe == "q":
        break
    
    # Versuchen, die Eingabe in eine Zahl zu konvertieren und zur Liste hinzufügen
    try:
        zahl = int(eingabe)
        zahlen.append(zahl)
    except ValueError:
        print("Ungültige Eingabe. Bitte geben Sie eine ganze Zahl ein.")
        continue
    
    # Liste aufsteigend sortieren
    zahlen.sort()
    
    # Ausgabe der sortierten Liste
    print("Sortierte Liste:", zahlen)

# Initialisieren der Summe mit 0
summe = 0

# Schleife von 1 bis 100
for zahl in range(1, 101):
    # Die aktuelle Zahl zur Summe hinzufügen
    summe += zahl

# Ausgabe der Summe
print("Die Summe von 1 bis 100 ist:", summe)

def fahrenheit(T_in_celsius):
	print(t, ": ", (T_in_celsius * 9 / 5) + 32)

for t in (22.6, 25.8, 27.3, 29.8):
    fahrenheit(t)

df = pd.read_csv("/content/samplefilehub.txt", error_bad_lines=False)
print(df)

import math

# Quadratwurzel von 16
print(math.sqrt(16))

# Natürlicher Logarithmus von e
print(math.log(math.e))

# Exponential von 2
print(math.exp(2))

# 10er-Logarithmus von 100
print(math.log10(100))

# Fakultät von 5
print(math.factorial(5))

# Größter gemeinsamer Teiler von 30 und 567
print(math.gcd(30, 567))

# Konstante pi
print(math.pi)

# Konstante e
print(math.e)

df = open("/content/samplefilehub.txt")
for f in df:
  print(f)